compilers:
- compiler:
    spec: gcc@10.1.0
    paths:
      cc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/gcc-10.1.0-yhlctewb76onnj73rzsgwzz3psdrpx4x/bin/gcc
      cxx: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/gcc-10.1.0-yhlctewb76onnj73rzsgwzz3psdrpx4x/bin/g++
      f77: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/gcc-10.1.0-yhlctewb76onnj73rzsgwzz3psdrpx4x/bin/gfortran
      fc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/gcc-10.1.0-yhlctewb76onnj73rzsgwzz3psdrpx4x/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@2022.1.0
    paths:
      cc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/icx
      cxx: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/dpcpp
      f77: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/ifx
      fc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/ifx
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.6.0
    paths:
      cc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/intel64/icc
      cxx: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/intel64/icpc
      f77: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/intel64/ifort
      fc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2022.1.0
    paths:
      cc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/icx
      cxx: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/icpx
      f77: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/ifx
      fc: /sfs/nopt/nrel/apps/compilers/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/intel-oneapi-compilers-2022.1.0-xg6gkwlurwzecjefls2m4s3t73r4cmc7/compiler/2022.1.0/linux/bin/ifx
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
